name = "Island Build Pack"
author = "Skyibis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8b259ab8239aabf7a03d72c5d25b67d3b2532e39a663df85f02dc2c0ab3e594"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
