name = "Island Build Pack"
author = "Skyibis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "164fd969d600bc4ed1ece899205aa80dbeb3eb168bca31e59bea7ceb7d82c971"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
