name = "Island Build Pack"
author = "Skyibis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0b7f4b18c9ff8bc59efa662789383adcc3f54e7c361425d4382ed64e428259bc"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
