name = "Island Build Pack"
author = "Skyibis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3837443c7ae897554ec52a07b2a89151db2957b40bc20b94aab0622cdc66715"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
