name = "Island Build Pack"
author = "Skyibis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "959403a7476d92cb0bebb62163068a2822df82bb1bfed154e34bf210ca045d09"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
