name = "Island Build Pack"
author = "Skyibis"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bffad1fa786a170ae27bf4176436f490f066759dcea6ccb205e4f5ae702c2113"

[versions]
fabric = "0.17.2"
minecraft = "1.21.1"
